from jinja2 import Environment, FileSystemLoader


def generate_plugin(emoji_dir, emoji_load_limit):
    env = Environment(loader=FileSystemLoader("./"))
    template = env.get_template("universal-emoji.jinja2")
    AUTOGENERATED_FILE_WARNING = "// WARNING: this file is autogenerated, if you want your changes to not be overwritten, modify the template or generator script"
    output_from_parsed_template = template.render(
        autogenerated_warning=AUTOGENERATED_FILE_WARNING,
        emoji_dir=emoji_dir,
        emoji_load_limit=emoji_load_limit,
    )
    with open("universal-emoji.autogenerate.ini", "w") as fh:
        fh.write(output_from_parsed_template)
